export const postgresToGraphql = {
  _bool: "GraphQLList(GraphQLBoolean)",
  _float4: "GraphQLList(GraphQLFloat)",
  _float8: "GraphQLList(GraphQLFloat)",
  _int2: "GraphQLList(GraphQLInt)",
  _int4: "GraphQLList(GraphQLInt)",
  _int8: "GraphQLList(GraphQLInt)",
  _text: "GraphQLList(GraphQLString)",
  bool: "GraphQLBoolean",
  float4: "GraphQLFloat",
  float8: "GraphQLFloat",
  int2: "GraphQLInt",
  int4: "GraphQLInt",
  int8: "GraphQLInt",
  text: "GraphQLString",
  timestamp: "GraphQLDate",
  timestamptz: "GraphQLDate",
  date: "GraphQLDate",
  varchar: "GraphQLString",
  jsonb: "GraphQLJSONObject",
  json: "GraphQLJSONObject",
  uuid: "GraphQLString",
  time: "GraphQLString",
} as const;

export const postgresToTS = {
  _bool: "boolean[]",
  _float4: "number[]",
  _float8: "number[]",
  _int2: "number[]",
  _int4: "number[]",
  _int8: "number[]",
  _text: "string[]",
  bool: "boolean",
  float4: "number",
  float8: "number",
  int2: "number",
  int4: "number",
  int8: "number",
  text: "string",
  timestamp: "Date",
  timestamptz: "Date",
  date: "Date",
  varchar: "string",
  jsonb: "unknown",
  json: "unknown",
  uuid: "string",
  time: "string",
} as const;
